version: '3.7'
services:
  nextjs:
    container_name: nextjs
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./

  caddy:
    image: caddy/caddy:2.3.0-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - '8080:8080'
      # - '443:443'
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
